In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("dataset_facebook.csv",sep=";")

In [4]:
df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [6]:
df.columns

Index(['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday',
       'Post Hour', 'Paid', 'Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'comment', 'like', 'share', 'Total Interactions'],
      dtype='object')

In [7]:
df.describe

<bound method NDFrame.describe of      Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  \
0              139441   Photo         2          12             4          3
1              139441  Status         2          12             3         10
2              139441   Photo         3          12             3          3
3              139441   Photo         2          12             2         10
4              139441   Photo         2          12             2          3
5              139441  Status         2          12             1          9
6              139441   Photo         3          12             1          3
7              139441   Photo         3          12             7          9
8              139441  Status         2          12             7          3
9              139441   Photo         3          12             6         10
10             139441  Status         2          12             5         10
11             139441   Photo         2          12             5         10
12             139441   Photo         2          12             5         10
13             139441   Photo         2          12             5          3
14             138414   Photo         2          12             4          5
15             138414  Status         2          12             3         10
16             138414   Photo         3          12             3          3
17             138414   Photo         1          12             2         12
18             138414  Status         3          12             2          3
19             138414   Photo         3          12             1         11
20             138414   Photo         2          12             1          3
21             138414   Photo         1          12             7         10
22             138414    Link         1          12             7         10
23             138414   Photo         3          12             7          3
24             138414  Status         2          12             6         10
25             138458  Status         2          12             6          3
26             138458  Status         2          12             5         11
27             138458   Photo         3          12             5          3
28             138895   Photo         2          12             5          3
29             138895   Video         1          12             4         11
..                ...     ...       ...         ...           ...        ...
470             91437    Link         1           2             3         13
471             91330   Photo         3           2             3          3
472             91223   Photo         1           2             2         13
473             91116   Photo         3           2             2          4
474             91009   Photo         1           2             1         12
475             86909   Photo         3           1             6         16
476             86909   Photo         1           1             6         10
477             86909    Link         1           1             6          4
478             86909   Photo         3           1             5         13
479             86909   Photo         3           1             5          4
480             86909   Photo         2           1             4         11
481             86491    Link         1           1             4          4
482             86491   Photo         3           1             3         10
483             86491   Photo         2           1             3          3
484             86491   Photo         3           1             2          7
485             86491    Link         1           1             2          2
486             85979   Photo         3           1             1         12
487             85979   Photo         3           1             1          2
488             85979   Photo         3           1             7         10
489             85979   Photo         3           1             7          2
490             85979   Photo         3           1             6         11
491             85979   Photo         3           1             6          3
492             85979    Link         1           1             5         11
493             85093   Photo         3           1             1          2
494             85093   Photo         3           1             7         10
495             85093   Photo         3           1             7          2
496             81370   Photo         2           1             5          8
497             81370   Photo         1           1             5          2
498             81370   Photo         3           1             4         11
499             81370   Photo         2           1             4          4

     Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
0     0.0                       2752                             5091
1     0.0                      10460                            19057
2     0.0                       2413                             4373
3     1.0                      50128                            87991
4     0.0                       7244                            13594
5     0.0                      10472                            20849
6     1.0                      11692                            19479
7     1.0                      13720                            24137
8     0.0                      11844                            22538
9     0.0                       4694                             8668
10    0.0                      21744                            42334
11    0.0                       3112                             5590
12    0.0                       2847                             5133
13    0.0                       2549                             4896
14    1.0                      22784                            39941
15    0.0                      10060                            19680
16    0.0                       1722                             2981
17    1.0                      53264                           111785
18    0.0                       3930                             7509
19    0.0                       1591                             2825
20    0.0                       2848                             5066
21    0.0                       1384                             2467
22    0.0                       3454                             6853
23    0.0                       2723                             4888
24    0.0                       8488                            15294
25    0.0                       8284                            15104
26    0.0                      19552                            34143
27    0.0                       2478                             4306
28    0.0                       9560                            18264
29    1.0                      36208                            61262
..    ...                        ...                              ...
470   0.0                       9356                            14986
471   0.0                       7732                            13264
472   0.0                       5240                             8893
473   1.0                       7132                            12060
474   0.0                      21928                            39641
475   1.0                       5754                             9238
476   1.0                      37088                            10966
477   0.0                      39600                             7927
478   0.0                       5536                             8745
479   0.0                       6056                            10325
480   0.0                      11484                            20696
481   1.0                       4938                             7910
482   0.0                      66784                             9456
483   0.0                       5526                             8779
484   0.0                       5040                             8367
485   0.0                       5168                             8371
486   0.0                       5034                             8030
487   0.0                       4908                             7491
488   0.0                       9700                            17442
489   0.0                       4800                             7754
490   0.0                       5280                             8703
491   1.0                       6184                            10228
492   0.0                      45920                             5808
493   0.0                       8412                            13960
494   0.0                       5400                             9218
495   0.0                       4684                             7536
496   0.0                       3480                             6229
497   0.0                       3778                             7216
498   0.0                       4156                             7564
499   NaN                       4188                             7292

     Lifetime Engaged Users  Lifetime Post Consumers  \
0                       178                      109
1                      1457                     1361
2                       177                      113
3                      2211                      790
4                       671                      410
5                      1191                     1073
6                       481                      265
7                       537                      232
8                      1530                     1407
9                       280                      183
10                     4258                     4100
11                      208                      127
12                      193                      115
13                      249                      134
14                      887                      337
15                     1264                     1209
16                      163                      123
17                     1706                     1103
18                      130                       86
19                      121                       88
20                      200                      142
21                       15                       15
22                      118                      104
23                      176                      118
24                     1341                     1270
25                     1521                     1462
26                     2806                     2531
27                      212                      124
28                      973                      559
29                     1141                     1068
..                      ...                      ...
470                     448                      381
471                    1066                     1002
472                     857                      837
473                    1004                      944
474                    1512                     1479
475                    1179                     1143
476                    2728                     2288
477                     572                      496
478                    1141                     1099
479                    1117                     1078
480                    1762                     1635
481                      66                       63
482                    2969                     2833
483                    1096                     1058
484                    1062                     1023
485                      66                       59
486                    1020                      993
487                     957                      937
488                    1407                     1271
489                     975                      938
490                     951                      911
491                     956                      901
492                     753                      655
493                    1179                     1111
494                     810                      756
495                     733                      708
496                     537                      508
497                     625                      572
498                     626                      574
499                     564                      524

     Lifetime Post Consumptions  \
0                           159
1                          1674
2                           154
3                          1119
4                           580
5                          1389
6                           364
7                           305
8                          1692
9                           250
10                         4540
11                          145
12                          133
13                          168
14                          417
15                         1425
16                          148
17                         1655
18                          112
19                          111
20                          184
21                           20
22                          130
23                          143
24                         1489
25                         1711
26                         3420
27                          149
28                          885
29                         1728
..                          ...
470                         505
471                        1336
472                        1020
473                        1226
474                        1837
475                        1452
476                        3183
477                         581
478                        1461
479                        1427
480                        2741
481                          70
482                        3645
483                        1399
484                        1348
485                          71
486                        1243
487                        1153
488                        2007
489                        1278
490                        1237
491                        1140
492                         763
493                        1632
494                        1003
495                         985
496                         687
497                         795
498                         832
499                         743

     Lifetime Post Impressions by people who have liked your Page  \
0                                                 3078
1                                                11710
2                                                 2812
3                                                61027
4                                                 6228
5                                                16034
6                                                15432
7                                                19728
8                                                15220
9                                                 4309
10                                               37849
11                                                3887
12                                                3779
13                                                3631
14                                               34415
15                                               17272
16                                                1868
17                                               92512
18                                                5009
19                                                2116
20                                                3561
21                                                2196
22                                                6282
23                                                2964
24                                                9684
25                                               10266
26                                               17748
27                                                2612
28                                                9217
29                                               30131
..                                                 ...
470                                              13919
471                                               8753
472                                               7420
473                                               8294
474                                               6338
475                                               6101
476                                              66311
477                                              12522
478                                               5225
479                                               6823
480                                               8774
481                                               6625
482                                              17809
483                                               5732
484                                               5485
485                                               7041
486                                               5340
487                                               4642
488                                               8872
489                                               4932
490                                               5757
491                                               6085
492                                              15766
493                                               8632
494                                               5654
495                                               4750
496                                               3961
497                                               4742
498                                               4534
499                                               3861

     Lifetime Post reach by people who like your Page  \
0                                                1640
1                                                6112
2                                                1503
3                                               32048
4                                                3200
5                                                7852
6                                                9328
7                                               11056
8                                                7912
9                                                2324
10                                              18952
11                                               2174
12                                               2072
13                                               1917
14                                              19312
15                                               8548
16                                               1050
17                                              39776
18                                               2410
19                                               1161
20                                               1963
21                                               1172
22                                               3100
23                                               1621
24                                               5244
25                                               5372
26                                               9824
27                                               1443
28                                               4748
29                                              14112
..                                                ...
470                                              8460
471                                              4880
472                                              4232
473                                              4736
474                                              3672
475                                              3546
476                                             34352

In [8]:
# a. Create data subsets

In [9]:
subset1 = df[['Type', 'Category', 'like', 'share']]
subset1.head()

     Type  Category    like  share
0   Photo         2    79.0   17.0
1  Status         2   130.0   29.0
2   Photo         3    66.0   14.0
3   Photo         2  1572.0  147.0
4   Photo         2   325.0   49.0

In [51]:
df[['Type','like']].head()

     Type    like
0   Photo    79.0
1  Status   130.0
2   Photo    66.0
3   Photo  1572.0
4   Photo   325.0

In [11]:
subset2 = df[df['like'] > 100]
subset2.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279

In [12]:
df.loc[[1,3,7]]

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339

In [13]:
subset4 = df.iloc[1:10, 1:6]
subset4

     Type  Category  Post Month  Post Weekday  Post Hour
1  Status         2          12             3         10
2   Photo         3          12             3          3
3   Photo         2          12             2         10
4   Photo         2          12             2          3
5  Status         2          12             1          9
6   Photo         3          12             1          3
7   Photo         3          12             7          9
8  Status         2          12             7          3
9   Photo         3          12             6         10

In [14]:
df.loc[5:8]

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192

In [15]:
df.loc[1:7,['like','share']]

     like  share
1   130.0   29.0
2    66.0   14.0
3  1572.0  147.0
4   325.0   49.0
5   152.0   33.0
6   249.0   27.0
7   325.0   14.0

In [16]:
# b. Merge Data

In [17]:
df1 = pd.DataFrame({
    'employee': ['Bob','Jake','Lisa','Sue'],
    'group': ['Accounting','Engineering','Engineering','HR']
})

In [18]:
df2 = pd.DataFrame({
    'employee': ['Lisa','Bob','Jake','Sue'],
    'hire_date': [2004,2008,2012,2014]
})

In [19]:
merged = pd.merge(df1, df2)

In [20]:
merged

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [21]:
df3 = pd.DataFrame({
    'group': ['Accounting','Engineering','HR'],
    'supervisor': ['Carly','Guido','Steve']
})

In [22]:
merged2 = pd.merge(merged, df3)

In [23]:
merged2

  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

In [24]:
subset1 = df.loc[1:5,['Category','like','share','Type']]
subset1

   Category    like  share    Type
1         2   130.0   29.0  Status
2         3    66.0   14.0   Photo
3         2  1572.0  147.0   Photo
4         2   325.0   49.0   Photo
5         2   152.0   33.0  Status

In [30]:
subset2 = df.loc[5:10,['Category','like','share','Type']]
subset2

    Category   like  share    Type
5          2  152.0   33.0  Status
6          3  249.0   27.0   Photo
7          3  325.0   14.0   Photo
8          2  161.0   31.0  Status
9          3  113.0   26.0   Photo
10         2  233.0   19.0  Status

In [31]:
print(subset1, '\n\n', subset2)

   Category    like  share    Type
1         2   130.0   29.0  Status
2         3    66.0   14.0   Photo
3         2  1572.0  147.0   Photo
4         2   325.0   49.0   Photo
5         2   152.0   33.0  Status

     Category   like  share    Type
5          2  152.0   33.0  Status
6          3  249.0   27.0   Photo
7          3  325.0   14.0   Photo
8          2  161.0   31.0  Status
9          3  113.0   26.0   Photo
10         2  233.0   19.0  Status

In [32]:
merge_set = pd.concat([subset1, subset2], axis=0)
print(merge_set)

    Category    like  share    Type
1          2   130.0   29.0  Status
2          3    66.0   14.0   Photo
3          2  1572.0  147.0   Photo
4          2   325.0   49.0   Photo
5          2   152.0   33.0  Status
5          2   152.0   33.0  Status
6          3   249.0   27.0   Photo
7          3   325.0   14.0   Photo
8          2   161.0   31.0  Status
9          3   113.0   26.0   Photo
10         2   233.0   19.0  Status

In [33]:
merge_set.shape

(11, 4)

In [34]:
# Sorting Data

In [35]:
df.sort_values(by="like").head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
21,138414,Photo,1,12,7,10,0.0,1384,2467,15,15,20,2196,1172,15,0,0.0,0.0,0
417,104070,Photo,1,3,3,10,0.0,1874,2474,25,25,31,1483,1062,15,0,0.0,0.0,0
100,137020,Photo,1,10,4,9,1.0,1357,2453,37,37,55,2154,1120,32,0,0.0,0.0,0
76,137893,Photo,1,11,3,2,0.0,1228,2392,17,17,19,2392,1228,17,0,0.0,0.0,0
441,98195,Photo,1,3,5,4,1.0,1845,2670,9,9,9,1614,1008,9,0,0.0,0.0,0

In [36]:
df.sort_values(by="like", ascending=False).head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334
379,111620,Photo,3,4,1,14,1.0,105632,147918,3984,2254,3391,48575,27328,1936,51,1998.0,128.0,2177
349,117764,Photo,3,5,5,13,0.0,81856,124753,3000,1637,2718,52477,27392,1756,45,1639.0,122.0,1806
168,135428,Photo,1,9,3,10,0.0,41984,68290,3370,2420,4074,34802,20928,2126,144,1622.0,208.0,1974
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777

In [23]:
df.sort_values(by=["like","share"]).head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
21,138414,Photo,1,12,7,10,0.0,1384,2467,15,15,20,2196,1172,15,0,0.0,0.0,0
76,137893,Photo,1,11,3,2,0.0,1228,2392,17,17,19,2392,1228,17,0,0.0,0.0,0
100,137020,Photo,1,10,4,9,1.0,1357,2453,37,37,55,2154,1120,32,0,0.0,0.0,0
417,104070,Photo,1,3,3,10,0.0,1874,2474,25,25,31,1483,1062,15,0,0.0,0.0,0
441,98195,Photo,1,3,5,4,1.0,1845,2670,9,9,9,1614,1008,9,0,0.0,0.0,0

In [37]:
df.sort_index().head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [38]:
# d. Transposing Data

In [39]:
df.head(10).T

,0,1,2,3,4,5,6,7,8,9
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo
Category,2,2,3,2,2,2,3,3,2,3
Post Month,12,12,12,12,12,12,12,12,12,12
Post Weekday,4,3,3,2,2,1,1,7,7,6
Post Hour,3,10,3,10,3,9,3,9,3,10
Paid,0,0,0,1,0,0,1,1,0,0
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280
Lifetime Post Consumers,109,1361,113,790,410,1073,265,232,1407,183
Lifetime Post Consumptions,159,1674,154,1119,580,1389,364,305,1692,250
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228,16034,15432,19728,15220,4309
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200,7852,9328,11056,7912,2324
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396,1016,379,422,1250,199
comment,4,5,0,58,19,1,3,0,0,3
like,79,130,66,1572,325,152,249,325,161,113
share,17,29,14,147,49,33,27,14,31,26
Total Interactions,100,164,80,1777,393,186,279,339,192,142

In [40]:
df.T.head()

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,85979,85979,85979,85093,85093,85093,81370,81370,81370,81370
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,3,3,1,3,3,3,2,1,3,2
Post Month,12,12,12,12,12,12,12,12,12,12,...,1,1,1,1,1,1,1,1,1,1
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,6,6,5,1,7,7,5,5,4,4

In [41]:
# e. Shape and reshape Data

In [50]:
df.shape

(500, 19)

In [44]:

selective_df=pd.DataFrame(df.iloc[0:3],columns=['like','share','Category','Type'])
print(selective_df.head(5))

    like  share  Category    Type
0   79.0   17.0         2   Photo
1  130.0   29.0         2  Status
2   66.0   14.0         3   Photo

In [45]:

sub1 = df.loc[0:5,['Category', 'Post Month','Post Hour', 'Paid']]

sub1.melt(id_vars=['Category'])

    Category    variable  value
0          2  Post Month   12.0
1          2  Post Month   12.0
2          3  Post Month   12.0
3          2  Post Month   12.0
4          2  Post Month   12.0
5          2  Post Month   12.0
6          2   Post Hour    3.0
7          2   Post Hour   10.0
8          3   Post Hour    3.0
9          2   Post Hour   10.0
10         2   Post Hour    3.0
11         2   Post Hour    9.0
12         2        Paid    0.0
13         2        Paid    0.0
14         3        Paid    0.0
15         2        Paid    1.0
16         2        Paid    0.0
17         2        Paid    0.0

In [46]:
pivote_table=pd.pivot_table(selective_df,index=['Category'])
print(pivote_table)

           like  share
Category
2         104.5   23.0
3          66.0   14.0

In [47]:
pivote_table.shape

(2, 2)

In [48]:
pivote_table.reset_index(inplace=True)
print(pivote_table)

   Category   like  share
0         2  104.5   23.0
1         3   66.0   14.0

In [49]:
pivote_table.melt(id_vars=['like','share'])

    like  share  variable  value
0  104.5   23.0  Category      2
1   66.0   14.0  Category      3